name: Curso Cypress

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Config Cypress
        run: cp ci/cypress.json cypress.json

      - name: Copy env's
        run: cp ci/cypress.env.json.example cypress.env.json

      - name: Install dependencies
        run: npm i

      - name: Run tests
        run: npx cypress run